---
- name: Create new VMs on VMware provider
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    provider_id: "{{ vmware_provider_id  | default('1000000000003') }}"
    max_retries: 9
    retry_interval: 20
    db_vm: "{{ 'db-' + manageiq.service | replace('/','-') }}"
    app_vm: "{{ 'app-' + manageiq.service | replace('/','-') }}"
    tags_db:
      env:  "{{ tags_env  | default('prod') }}"
      type: "{{ tags_type | default('db') }}"
    tags_app:
      env:  "{{ tags_env  | default('prod') }}"
      type: "{{ tags_type | default('app') }}"
    wait_for_ssh: False
    max_retries: 9
    retry_interval: 20

  tasks:
    - debug: var=vcenter_hostname
    - debug: var=esxi_host
    - debug: var=datacenter
    - debug: var=template
    - debug: var=manageiq.api_url
    - debug: var=manageiq.api_token
    - debug: var=manageiq.service
    - debug: var=db_vm
    - debug: var=app_vm

    - name: Set the Provider URL
      set_fact:
        provider_url: "{{ manageiq.api_url }}/api/providers/{{ provider_id }}"

    - name: Set the Service URL
      set_fact:
        svc_url: "/api/{{ manageiq.service }}"

    - debug: var=svc_url

    - name: Launch APP and DB instances
      vsphere_guest:
        validate_certs: no
        vcenter_hostname: "{{ vcenter_hostname }}"
        guest: "{{ item }}"
        power_on_after_clone: yes
        from_template: yes
        template_src: "{{ template }}"
        esxi:
          datacenter: "{{ datacenter }}"
          hostname: "{{ esxi_host }}"
      with_items:
        - "{{ db_vm }}"
        - "{{ app_vm }}"

    - name: Wait for VMs to get their IP addresses
      vsphere_guest:
        validate_certs: no
        vcenter_hostname: "{{ vcenter_hostname }}"
        guest: "{{ item }}"
        vmware_guest_facts: yes
      register: new_vms
      with_items:
        - "{{ db_vm }}"
        - "{{ app_vm }}"
      until: new_vms.results[0].ansible_facts.hw_eth0.ipaddresses and new_vms.results[1].ansible_facts.hw_eth0.ipaddresses
      retries: "{{max_retries}}"
      delay: "{{retry_interval}}"

    - name: Gather the facts for App and DB VMs
      vsphere_guest:
        validate_certs: no
        vcenter_hostname: "{{ vcenter_hostname }}"
        guest: "{{ item }}"
        vmware_guest_facts: yes
      register: new_vms
      with_items:
        - "{{ db_vm }}"
        - "{{ app_vm }}"

    - debug: var=new_vms

    - set_fact: db_vm_uuid="{{ new_vms.results[0].ansible_facts.hw_product_uuid }}"
    - set_fact: app_vm_uuid="{{ new_vms.results[1].ansible_facts.hw_product_uuid }}"

    - debug: var=db_vm_uuid
    - debug: var=app_vm_uuid

    - name: Refresh provider in CloudForms
      uri:
        url: "{{ provider_url }}"
        method: POST
        body:
          action: refresh
        body_format: json
        validate_certs: False
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type: "application/json"
        status_code: 200
      register: output
    - debug: var=output

    - name: set the task href
      set_fact:
        task_url: "{{ output.json.task_href}}"
    - debug: var=task_url

    - name: Wait for the refresh to end
      uri:
        url: "{{ task_url }}"
        method: GET
        validate_certs: False
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type: "application/json"
        status_code: 200
      register: task_result
      until: task_result.json.state == 'Finished' or task_result.json.status == 'Error'
      failed_when: task_result.json.status == 'Error'
      retries: "{{max_retries}}"
      delay: "{{retry_interval}}"
    - debug: var=task_result

    - set_fact: find_db_vm_url="{{ manageiq.api_url }}/api/vms?expand=resources&attributes=href,uid_ems&filter[]=uid_ems='{{ db_vm_uuid }}'"
    - set_fact: find_app_vm_url="{{ manageiq.api_url }}/api/vms?expand=resources&attributes=href,uid_ems&filter[]=uid_ems='{{ app_vm_uuid }}'"

    - debug: var=find_db_vm_url
    - debug: var=find_app_vm_url

    - name: Call to CloudForms to find href for vm_uuids
      uri:
        url: "{{ item }}"
        method: GET
        validate_certs: no
        headers:
           X-Auth-Token: "{{ manageiq.api_token }}"
           Content-Type: "application/json"
        body_format: json
        return_content: yes
      register: token_output
      with_items:
        - "{{ find_db_vm_url }}"
        - "{{ find_app_vm_url }}"

    - debug: var=token_output

    - set_fact: cf_db_vm_href="{{ token_output.results[0].json.resources[0].href }}"
    - set_fact: cf_app_vm_href="{{ token_output.results[1].json.resources[0].href }}"

    - debug: var=cf_db_vm_href
    - debug: var=cf_app_vm_href

    - name: Create an array of vms
      set_fact:
        vms: "{{ vms|default([]) + [ { 'href': svc_url, 'resource':  { 'href': item } } ] }}"
      with_items:
        - "{{ cf_db_vm_href }}"
        - "{{ cf_app_vm_href }}"

    - debug: var=vms

    - name: Register vm with the service
      uri:
        url: "{{ manageiq.api_url }}/api/services"
        method: POST
        body_format: json
        body:
          action: add_resource
          resources : "{{ vms }}"
        validate_certs: False
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type: "application/json"
        status_code: 200
      register: output

    - debug: var=output.json.results[0].success
